import * as fs from "fs"
import { generatePackageReadme } from "./src/storybook_utils/helpers"

const rootPath = "src"

const exportFolders = ["components", "hooks", "helpers"]

exportFolders.forEach((exportFolder) => {
  const exportFolderPath = `${rootPath}/${exportFolder}`
  fs.readdir(exportFolderPath, function (_, items) {
    items.forEach(async (item) => {
      const modulePath = `${exportFolderPath}/${item}`
      const configPath = `${modulePath}/stories/config.ts`
      if (fs.existsSync(configPath)) {
        const { default: config } = await import(
          `${import.meta.url}/../${configPath}`
        )

        fs.writeFileSync(
          `${modulePath}/README.md`,
          generatePackageReadme(config),
        )
      }
    })
  })
  const rootTemplate = fs.readFileSync("./README_TEMPLATE.md", {
    encoding: "utf8",
    flag: "r",
  })

  const rootReadme = rootTemplate
    .replace(
      /^/,
      "<!--- Autogenerated Readme. Do not edit. Edit the README_TEMPLATE.md file instead. --->\n",
    )
    .replace("INSERT_CONTENTS_HERE", "test")

  fs.writeFileSync(`./README.md`, rootReadme)
})

console.log("Done generating readmes")
