export const LS_KEY_TWITCH_AUTH_TOKEN = "lb_twitch_auth_token"
export const LS_KEY_TWITCH_CSRF_TOKEN = "lb_twitch_auth_uid"
export const LS_KEY_TWITCH_CHANNEL = "lb_twitch_auth_channel"
export const LS_KEY_PLAYBACK_PAGE_INDEX = "lb_playback_page"
export const LS_KEY_PLAYBACK_CONTENTS = "lb_playback_contents"
export const LS_KEY_PLAYBACK_BACKGROUND = "lb_playback_background"
