const StoriesTemplate = `// Autogenerated story file. Do not edit this directly.
// Instead edit the story's individual "stories/config" file, the demo components or the storiesTemplate
import type { Meta, StoryObj } from "@storybook/react"
INSERT_COMPONENT_IMPORT_HERE
import { merge } from "utils"
import { getStoryMeta } from "storybook_utils/helpers"
import storyConfig from "./config"

let meta = {
  title: "INSERT_STORY_TITLE_HERE",
  component: INSERT_COMPONENT_HERE,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component: INSERT_DESCRIPTION_HERE,
      },
    },
    deepControls: { enabled: true },
  },
  tags: ["autodocs"],
} as Meta<typeof INSERT_COMPONENT_HERE>

if (storyConfig.metaMutations) {
  meta = merge(meta, storyConfig.metaMutations)
}

export default meta

type Story = StoryObj<typeof INSERT_COMPONENT_HERE>

INSERT_STORIES_HERE
`

export default StoriesTemplate
